# -*- coding: utf-8 -*-
"""Assignment5(1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Rf4qO2-3-PrCp3Os2gwW8yKaD7Gn1Vi
"""

# -*- coding: utf-8 -*-
"""ChallengeProblem3_2.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1app0wxrbBoJ1MbL_L1S22a4zzsSN741I
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-5, 5, 100)

y = 3*x**2 -5*x + 2 

plt.plot(x,y,label='y=3$x^2$-5x+2')
plt.grid()

plt.plot(5/2,-1, 'o')
plt.text(0.83,-0.5,'c')

#show plot
plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend()
plt.ylim([0,5])
plt.show()